name = "sinama"
main = "worker/index.ts"
compatibility_date = "2024-09-23"

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[durable_objects]
bindings = [
  { name = "ROOM_DO", class_name = "RoomDurableObject" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RoomDurableObject"]
